# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e7d7dcd55bf15afe7df353a1c8507dd6"
name = "Scalysis"
handle = "scalysis-v1"
application_url = "https://scalysis-public.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_all_orders,write_orders"

[auth]
redirect_urls = [
  "https://scalysis-public.onrender.com/auth/callback",
  "https://scalysis-public.onrender.com/auth/shopify/callback",
  "https://scalysis-public.onrender.com/api/auth/callback"
]

[pos]
embedded = false
